// Deploy script using frontend's genlayer-js (0.28.2) for Bradbury testnet
import { createClient, createAccount } from "../frontend/node_modules/genlayer-js/dist/index.js";
import { testnetBradbury } from "../frontend/node_modules/genlayer-js/dist/chains/index.js";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const privateKey = process.env.PRIVATE_KEY;
if (!privateKey) throw new Error("PRIVATE_KEY env var is required");

const account = createAccount(privateKey);
const client = createClient({ chain: testnetBradbury, account });

const contractPath = path.resolve(__dirname, "../contracts/ai_code_auditor.py");
const contractCode = fs.readFileSync(contractPath, "utf-8");

console.log("Chain:", testnetBradbury.name, "ID:", testnetBradbury.id);
console.log("Deployer:", account.address);
console.log("Contract size:", contractCode.length, "bytes");

const deployHash = await client.deployContract({ code: contractCode, args: [] });
console.log("Deploy tx hash:", deployHash);
console.log("Waiting for receipt...");

const receipt = await client.waitForTransactionReceipt({
  hash: deployHash,
  retries: 200,
  interval: 5000,
});

console.log("Full receipt:", JSON.stringify(receipt, (_, v) => typeof v === "bigint" ? v.toString() : v, 2));

const contractAddress = receipt.contractAddress
  ?? receipt.to
  ?? receipt.data?.contractAddress
  ?? receipt.address;

console.log("Contract address:", contractAddress);

if (contractAddress && contractAddress !== "undefined") {
  const configPath = path.resolve(__dirname, "../frontend/src/lib/contract.ts");
  fs.writeFileSync(configPath, `// Bradbury testnet — auto-generated by deploy script
export const CONTRACT_ADDRESS = "${contractAddress}" as const;
export const CHAIN_ID = ${testnetBradbury.id};
`);
  console.log("Saved to contract.ts");
} else {
  console.log("Contract address not found in receipt. Check full receipt above.");
}
