// Deploy to GenLayer Studionet (simulator)
import { createClient, createAccount } from "../frontend/node_modules/genlayer-js/dist/index.js";
import { studionet } from "../frontend/node_modules/genlayer-js/dist/chains/index.js";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const privateKey = process.env.DEPLOYER_PRIVATE_KEY || "0x5b58a9baa0de4ff9db103511f97db85a82259be47ad983556077d18f0687846e";
const account = createAccount(privateKey);
const client = createClient({ chain: studionet, account });

const contractPath = path.resolve(__dirname, "../contracts/ai_code_auditor.py");
let contractCode = fs.readFileSync(contractPath, "utf-8");

// Studionet uses py-genlayer:latest
contractCode = contractCode.replace(
  /^# \{ "Depends": "py-genlayer:[^"]*" \}/,
  '# { "Depends": "py-genlayer:latest" }'
);

console.log("Chain:", studionet.name, "ID:", studionet.id);
console.log("Deployer:", account.address);
console.log("Contract first line:", contractCode.split("\n")[0]);

const deployHash = await client.deployContract({ code: contractCode, args: [] });
console.log("Deploy tx hash:", deployHash);
console.log("Waiting for receipt...");

const receipt = await client.waitForTransactionReceipt({
  hash: deployHash,
  retries: 60,
  interval: 3000,
});

console.log("Receipt:", JSON.stringify(receipt, (_, v) => typeof v === "bigint" ? v.toString() : v, 2).slice(0, 500));

// Studionet: contract address from creator nonce
const contractAddress = receipt.contractAddress ?? receipt.to ?? receipt.data?.contractAddress;
console.log("Contract address:", contractAddress);

if (contractAddress && contractAddress !== "0x0000000000000000000000000000000000000000") {
  const configPath = path.resolve(__dirname, "../frontend/src/lib/contract.ts");
  fs.writeFileSync(configPath, `// GenLayer Studionet — auto-generated by deploy script
export const CONTRACT_ADDRESS = "${contractAddress}" as const;
export const CHAIN_ID = ${studionet.id};
`);
  console.log("Saved to contract.ts");
}
