import { createClient, createAccount } from "genlayer-js";
import { testnetAsimov } from "genlayer-js/chains";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function deploy() {
  console.log("Deploying AICodeAuditor to Bradbury testnet...");

  const privateKey = process.env.PRIVATE_KEY as `0x${string}` | undefined;
  if (!privateKey) {
    throw new Error("PRIVATE_KEY env var is required");
  }

  const account = createAccount(privateKey);
  const client = createClient({ chain: testnetAsimov, account });

  const contractPath = path.resolve(__dirname, "../contracts/ai_code_auditor.py");
  const contractCode = fs.readFileSync(contractPath, "utf-8");

  console.log("Deployer address:", account.address);

  const deployHash = await client.deployContract({
    code: contractCode,
    args: [],
    gas: BigInt(10_000_000),
  });

  console.log("Deploy tx hash:", deployHash);
  console.log("Waiting for receipt (AI validators need ~2-5 min)...");

  const receipt = await client.waitForTransactionReceipt({
    hash: deployHash,
    retries: 200,
    interval: 5000,
  });

  const contractAddress = receipt.contractAddress;
  console.log("Contract deployed at:", contractAddress);

  const configPath = path.resolve(__dirname, "../frontend/src/lib/contract.ts");
  const configContent = `// Bradbury testnet (testnetAsimov) — auto-generated by deploy script
export const CONTRACT_ADDRESS = "${contractAddress}" as const;
export const CHAIN_ID = ${testnetAsimov.id};
`;
  fs.writeFileSync(configPath, configContent);
  console.log("Saved to:", configPath);

  return contractAddress;
}

deploy().catch((e) => { console.error(e); process.exit(1); });
